# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "discovery workspace create",
)
class Create(AAZCommand):
    """Create a Workspace
    """

    _aaz_info = {
        "version": "2026-06-01",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/microsoft.discovery/workspaces/{}", "2026-06-01"],
        ]
    }

    AZ_SUPPORT_NO_WAIT = True

    def _handler(self, command_args):
        super()._handler(command_args)
        return self.build_lro_poller(self._execute_operations, self._output)

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.resource_group = AAZResourceGroupNameArg(
            required=True,
        )
        _args_schema.workspace_name = AAZStrArg(
            options=["-n", "--name", "--workspace-name"],
            help="The name of the Workspace",
            required=True,
            fmt=AAZStrArgFormat(
                pattern="^[a-zA-Z0-9-]{3,24}$",
            ),
        )

        # define Arg Group "Properties"

        _args_schema = cls._args_schema
        _args_schema.agent_subnet_id = AAZResourceIdArg(
            options=["--agent-subnet-id"],
            arg_group="Properties",
            help="Agent Subnet ID for agent resources.",
        )
        _args_schema.customer_managed_keys = AAZStrArg(
            options=["--customer-managed-keys"],
            arg_group="Properties",
            help="Whether or not to use a customer managed key when encrypting data at rest",
            enum={"Disabled": "Disabled", "Enabled": "Enabled"},
        )
        _args_schema.key_vault_properties = AAZObjectArg(
            options=["--key-vault-properties"],
            arg_group="Properties",
            help="The key to use for encrypting data at rest when customer managed keys are enabled.",
        )
        _args_schema.log_analytics_cluster_id = AAZResourceIdArg(
            options=["--la-cluster-id", "--log-analytics-cluster-id"],
            arg_group="Properties",
            help="The Log Analytics Cluster to use for debug logs. This is required when Customer Managed Keys are enabled.",
        )
        _args_schema.private_endpoint_subnet_id = AAZResourceIdArg(
            options=["--pe-subnet-id", "--private-endpoint-subnet-id"],
            arg_group="Properties",
            help="Private Endpoint Subnet ID for private endpoint connections.",
        )
        _args_schema.public_network_access = AAZStrArg(
            options=["--public-network-access"],
            arg_group="Properties",
            help="Whether or not public network access is allowed for this resource. For security reasons, it is recommended to disable it whenever possible.",
            enum={"Disabled": "Disabled", "Enabled": "Enabled"},
        )
        _args_schema.supercomputer_ids = AAZListArg(
            options=["--supercomputer-ids"],
            arg_group="Properties",
            help="List of linked SuperComputers.",
        )
        _args_schema.workspace_identity = AAZObjectArg(
            options=["--workspace-identity"],
            arg_group="Properties",
            help="Identity IDs used for leveraging Workspace resources.",
        )
        _args_schema.workspace_subnet_id = AAZResourceIdArg(
            options=["--workspace-subnet-id"],
            arg_group="Properties",
            help="Function Subnet ID for workspace resources.",
        )

        key_vault_properties = cls._args_schema.key_vault_properties
        key_vault_properties.key_name = AAZStrArg(
            options=["key-name"],
            help="The Key Name in Key Vault",
            required=True,
        )
        key_vault_properties.key_vault_uri = AAZStrArg(
            options=["key-vault-uri"],
            help="The Key Vault URI",
            required=True,
        )
        key_vault_properties.key_version = AAZStrArg(
            options=["key-version"],
            help="The Key Version in Key Vault",
        )

        supercomputer_ids = cls._args_schema.supercomputer_ids
        supercomputer_ids.Element = AAZResourceIdArg()

        workspace_identity = cls._args_schema.workspace_identity
        workspace_identity.id = AAZResourceIdArg(
            options=["id"],
            help="The resource ID of the user assigned identity.",
            required=True,
        )

        # define Arg Group "Resource"

        _args_schema = cls._args_schema
        _args_schema.location = AAZResourceLocationArg(
            arg_group="Resource",
            help="The geo-location where the resource lives",
            required=True,
            fmt=AAZResourceLocationArgFormat(
                resource_group_arg="resource_group",
            ),
        )
        _args_schema.tags = AAZDictArg(
            options=["--tags"],
            arg_group="Resource",
            help="Resource tags.",
        )

        tags = cls._args_schema.tags
        tags.Element = AAZStrArg()
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        yield self.WorkspacesCreateOrUpdate(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class WorkspacesCreateOrUpdate(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [202]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200_201,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )
            if session.http_response.status_code in [200, 201]:
                return self.client.build_lro_polling(
                    self.ctx.args.no_wait,
                    session,
                    self.on_200_201,
                    self.on_error,
                    lro_options={"final-state-via": "azure-async-operation"},
                    path_format_arguments=self.url_parameters,
                )

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Discovery/workspaces/{workspaceName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "PUT"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
                **self.serialize_url_param(
                    "workspaceName", self.ctx.args.workspace_name,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2026-06-01",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        @property
        def content(self):
            _content_value, _builder = self.new_content_builder(
                self.ctx.args,
                typ=AAZObjectType,
                typ_kwargs={"flags": {"required": True, "client_flatten": True}}
            )
            _builder.set_prop("location", AAZStrType, ".location", typ_kwargs={"flags": {"required": True}})
            _builder.set_prop("properties", AAZObjectType)
            _builder.set_prop("tags", AAZDictType, ".tags")

            properties = _builder.get(".properties")
            if properties is not None:
                properties.set_prop("agentSubnetId", AAZStrType, ".agent_subnet_id")
                properties.set_prop("customerManagedKeys", AAZStrType, ".customer_managed_keys")
                properties.set_prop("keyVaultProperties", AAZObjectType, ".key_vault_properties")
                properties.set_prop("logAnalyticsClusterId", AAZStrType, ".log_analytics_cluster_id")
                properties.set_prop("privateEndpointSubnetId", AAZStrType, ".private_endpoint_subnet_id")
                properties.set_prop("publicNetworkAccess", AAZStrType, ".public_network_access")
                properties.set_prop("supercomputerIds", AAZListType, ".supercomputer_ids")
                properties.set_prop("workspaceIdentity", AAZObjectType, ".workspace_identity", typ_kwargs={"flags": {"required": True}})
                properties.set_prop("workspaceSubnetId", AAZStrType, ".workspace_subnet_id")

            key_vault_properties = _builder.get(".properties.keyVaultProperties")
            if key_vault_properties is not None:
                key_vault_properties.set_prop("keyName", AAZStrType, ".key_name", typ_kwargs={"flags": {"required": True}})
                key_vault_properties.set_prop("keyVaultUri", AAZStrType, ".key_vault_uri", typ_kwargs={"flags": {"required": True}})
                key_vault_properties.set_prop("keyVersion", AAZStrType, ".key_version")

            supercomputer_ids = _builder.get(".properties.supercomputerIds")
            if supercomputer_ids is not None:
                supercomputer_ids.set_elements(AAZStrType, ".")

            workspace_identity = _builder.get(".properties.workspaceIdentity")
            if workspace_identity is not None:
                workspace_identity.set_prop("id", AAZStrType, ".id", typ_kwargs={"flags": {"required": True}})

            tags = _builder.get(".tags")
            if tags is not None:
                tags.set_elements(AAZStrType, ".")

            return self.serialize_content(_content_value)

        def on_200_201(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200_201
            )

        _schema_on_200_201 = None

        @classmethod
        def _build_schema_on_200_201(cls):
            if cls._schema_on_200_201 is not None:
                return cls._schema_on_200_201

            cls._schema_on_200_201 = AAZObjectType()

            _schema_on_200_201 = cls._schema_on_200_201
            _schema_on_200_201.id = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200_201.location = AAZStrType(
                flags={"required": True},
            )
            _schema_on_200_201.name = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200_201.properties = AAZObjectType()
            _schema_on_200_201.system_data = AAZObjectType(
                serialized_name="systemData",
                flags={"read_only": True},
            )
            _CreateHelper._build_schema_system_data_read(_schema_on_200_201.system_data)
            _schema_on_200_201.tags = AAZDictType()
            _schema_on_200_201.type = AAZStrType(
                flags={"read_only": True},
            )

            properties = cls._schema_on_200_201.properties
            properties.agent_subnet_id = AAZStrType(
                serialized_name="agentSubnetId",
            )
            properties.customer_managed_keys = AAZStrType(
                serialized_name="customerManagedKeys",
            )
            properties.key_vault_properties = AAZObjectType(
                serialized_name="keyVaultProperties",
            )
            properties.log_analytics_cluster_id = AAZStrType(
                serialized_name="logAnalyticsClusterId",
            )
            properties.managed_on_behalf_of_configuration = AAZObjectType(
                serialized_name="managedOnBehalfOfConfiguration",
                flags={"read_only": True},
            )
            properties.managed_resource_group = AAZStrType(
                serialized_name="managedResourceGroup",
                flags={"read_only": True},
            )
            properties.private_endpoint_connections = AAZListType(
                serialized_name="privateEndpointConnections",
                flags={"read_only": True},
            )
            properties.private_endpoint_subnet_id = AAZStrType(
                serialized_name="privateEndpointSubnetId",
            )
            properties.provisioning_state = AAZStrType(
                serialized_name="provisioningState",
                flags={"read_only": True},
            )
            properties.public_network_access = AAZStrType(
                serialized_name="publicNetworkAccess",
            )
            properties.supercomputer_ids = AAZListType(
                serialized_name="supercomputerIds",
            )
            properties.workspace_api_uri = AAZStrType(
                serialized_name="workspaceApiUri",
                flags={"read_only": True},
            )
            properties.workspace_identity = AAZObjectType(
                serialized_name="workspaceIdentity",
                flags={"required": True},
            )
            properties.workspace_subnet_id = AAZStrType(
                serialized_name="workspaceSubnetId",
            )
            properties.workspace_ui_uri = AAZStrType(
                serialized_name="workspaceUiUri",
                flags={"read_only": True},
            )

            key_vault_properties = cls._schema_on_200_201.properties.key_vault_properties
            key_vault_properties.key_name = AAZStrType(
                serialized_name="keyName",
                flags={"required": True},
            )
            key_vault_properties.key_vault_uri = AAZStrType(
                serialized_name="keyVaultUri",
                flags={"required": True},
            )
            key_vault_properties.key_version = AAZStrType(
                serialized_name="keyVersion",
            )

            managed_on_behalf_of_configuration = cls._schema_on_200_201.properties.managed_on_behalf_of_configuration
            managed_on_behalf_of_configuration.mobo_broker_resources = AAZListType(
                serialized_name="moboBrokerResources",
                flags={"read_only": True},
            )

            mobo_broker_resources = cls._schema_on_200_201.properties.managed_on_behalf_of_configuration.mobo_broker_resources
            mobo_broker_resources.Element = AAZObjectType()

            _element = cls._schema_on_200_201.properties.managed_on_behalf_of_configuration.mobo_broker_resources.Element
            _element.id = AAZStrType()

            private_endpoint_connections = cls._schema_on_200_201.properties.private_endpoint_connections
            private_endpoint_connections.Element = AAZObjectType()

            _element = cls._schema_on_200_201.properties.private_endpoint_connections.Element
            _element.id = AAZStrType(
                flags={"read_only": True},
            )
            _element.name = AAZStrType(
                flags={"read_only": True},
            )
            _element.properties = AAZObjectType(
                flags={"client_flatten": True},
            )
            _element.system_data = AAZObjectType(
                serialized_name="systemData",
                flags={"read_only": True},
            )
            _CreateHelper._build_schema_system_data_read(_element.system_data)
            _element.type = AAZStrType(
                flags={"read_only": True},
            )

            properties = cls._schema_on_200_201.properties.private_endpoint_connections.Element.properties
            properties.group_ids = AAZListType(
                serialized_name="groupIds",
                flags={"read_only": True},
            )
            properties.private_endpoint = AAZObjectType(
                serialized_name="privateEndpoint",
            )
            properties.private_link_service_connection_state = AAZObjectType(
                serialized_name="privateLinkServiceConnectionState",
                flags={"required": True},
            )
            properties.provisioning_state = AAZStrType(
                serialized_name="provisioningState",
                flags={"read_only": True},
            )

            group_ids = cls._schema_on_200_201.properties.private_endpoint_connections.Element.properties.group_ids
            group_ids.Element = AAZStrType()

            private_endpoint = cls._schema_on_200_201.properties.private_endpoint_connections.Element.properties.private_endpoint
            private_endpoint.id = AAZStrType(
                flags={"read_only": True},
            )

            private_link_service_connection_state = cls._schema_on_200_201.properties.private_endpoint_connections.Element.properties.private_link_service_connection_state
            private_link_service_connection_state.actions_required = AAZStrType(
                serialized_name="actionsRequired",
            )
            private_link_service_connection_state.description = AAZStrType()
            private_link_service_connection_state.status = AAZStrType()

            supercomputer_ids = cls._schema_on_200_201.properties.supercomputer_ids
            supercomputer_ids.Element = AAZStrType()

            workspace_identity = cls._schema_on_200_201.properties.workspace_identity
            workspace_identity.client_id = AAZStrType(
                serialized_name="clientId",
                flags={"read_only": True},
            )
            workspace_identity.id = AAZStrType(
                flags={"required": True},
            )
            workspace_identity.principal_id = AAZStrType(
                serialized_name="principalId",
                flags={"read_only": True},
            )

            tags = cls._schema_on_200_201.tags
            tags.Element = AAZStrType()

            return cls._schema_on_200_201


class _CreateHelper:
    """Helper class for Create"""

    _schema_system_data_read = None

    @classmethod
    def _build_schema_system_data_read(cls, _schema):
        if cls._schema_system_data_read is not None:
            _schema.created_at = cls._schema_system_data_read.created_at
            _schema.created_by = cls._schema_system_data_read.created_by
            _schema.created_by_type = cls._schema_system_data_read.created_by_type
            _schema.last_modified_at = cls._schema_system_data_read.last_modified_at
            _schema.last_modified_by = cls._schema_system_data_read.last_modified_by
            _schema.last_modified_by_type = cls._schema_system_data_read.last_modified_by_type
            return

        cls._schema_system_data_read = _schema_system_data_read = AAZObjectType(
            flags={"read_only": True}
        )

        system_data_read = _schema_system_data_read
        system_data_read.created_at = AAZStrType(
            serialized_name="createdAt",
        )
        system_data_read.created_by = AAZStrType(
            serialized_name="createdBy",
        )
        system_data_read.created_by_type = AAZStrType(
            serialized_name="createdByType",
        )
        system_data_read.last_modified_at = AAZStrType(
            serialized_name="lastModifiedAt",
        )
        system_data_read.last_modified_by = AAZStrType(
            serialized_name="lastModifiedBy",
        )
        system_data_read.last_modified_by_type = AAZStrType(
            serialized_name="lastModifiedByType",
        )

        _schema.created_at = cls._schema_system_data_read.created_at
        _schema.created_by = cls._schema_system_data_read.created_by
        _schema.created_by_type = cls._schema_system_data_read.created_by_type
        _schema.last_modified_at = cls._schema_system_data_read.last_modified_at
        _schema.last_modified_by = cls._schema_system_data_read.last_modified_by
        _schema.last_modified_by_type = cls._schema_system_data_read.last_modified_by_type


__all__ = ["Create"]
