# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "monitor account issue add-or-update-alert",
)
class AddOrUpdateAlert(AAZCommand):
    """Add or update alerts in the issue

    :example: Add an alert to an issue
        az monitor account issue add-or-update-alert --azure-monitor-workspace-name myWorkspace -g myRG --issue-name myIssue --value "[{\"id\": \"/subscriptions/sub/resourceGroups/rg/providers/Microsoft.AlertsManagement/alerts/alert1\"}]"
    """

    _aaz_info = {
        "version": "2025-10-03",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/microsoft.monitor/accounts/{}/issues/{}/addorupdatealerts", "2025-10-03"],
        ]
    }

    def _handler(self, command_args):
        super()._handler(command_args)
        self._execute_operations()
        return self._output()

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.azure_monitor_workspace_name = AAZStrArg(
            options=["--azure-monitor-workspace-name"],
            help="The name of the Azure Monitor Workspace. The name is case insensitive",
            required=True,
            id_part="name",
            fmt=AAZStrArgFormat(
                pattern="^(?!-)[a-zA-Z0-9-]+[^-]$",
            ),
        )
        _args_schema.issue_name = AAZStrArg(
            options=["--issue-name"],
            help="The name of the IssueResource",
            required=True,
            id_part="child_name_1",
            fmt=AAZStrArgFormat(
                pattern="^(?!-)[a-zA-Z0-9-]+[^-]$",
            ),
        )
        _args_schema.resource_group = AAZResourceGroupNameArg(
            required=True,
        )

        # define Arg Group "Body"

        _args_schema = cls._args_schema
        _args_schema.value = AAZListArg(
            options=["--value"],
            arg_group="Body",
            help="A list of related alerts",
            required=True,
        )

        value = cls._args_schema.value
        value.Element = AAZObjectArg()

        _element = cls._args_schema.value.Element
        _element.id = AAZResourceIdArg(
            options=["id"],
            help="The alert ID",
            required=True,
        )
        _element.relevance = AAZStrArg(
            options=["relevance"],
            help="The alerts's relevance status",
            required=True,
            enum={"Irrelevant": "Irrelevant", "None": "None", "Relevant": "Relevant"},
        )
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        self.IssueAddOrUpdateAlerts(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class IssueAddOrUpdateAlerts(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200]:
                return self.on_200(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Monitor/accounts/{azureMonitorWorkspaceName}/issues/{issueName}/addOrUpdateAlerts",
                **self.url_parameters
            )

        @property
        def method(self):
            return "POST"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "azureMonitorWorkspaceName", self.ctx.args.azure_monitor_workspace_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "issueName", self.ctx.args.issue_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2025-10-03",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        @property
        def content(self):
            _content_value, _builder = self.new_content_builder(
                self.ctx.args,
                typ=AAZObjectType,
                typ_kwargs={"flags": {"required": True, "client_flatten": True}}
            )
            _builder.set_prop("value", AAZListType, ".value", typ_kwargs={"flags": {"required": True}})

            value = _builder.get(".value")
            if value is not None:
                value.set_elements(AAZObjectType, ".")

            _elements = _builder.get(".value[]")
            if _elements is not None:
                _elements.set_prop("id", AAZStrType, ".id", typ_kwargs={"flags": {"required": True}})
                _elements.set_prop("relevance", AAZStrType, ".relevance", typ_kwargs={"flags": {"required": True}})

            return self.serialize_content(_content_value)

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZObjectType()

            _schema_on_200 = cls._schema_on_200
            _schema_on_200.value = AAZListType(
                flags={"required": True},
            )

            value = cls._schema_on_200.value
            value.Element = AAZObjectType()

            _element = cls._schema_on_200.value.Element
            _element.added_at = AAZStrType(
                serialized_name="addedAt",
                flags={"read_only": True},
            )
            _element.id = AAZStrType(
                flags={"required": True},
            )
            _element.last_modified_at = AAZStrType(
                serialized_name="lastModifiedAt",
                flags={"read_only": True},
            )
            _element.origin = AAZObjectType(
                flags={"read_only": True},
            )
            _element.relevance = AAZStrType(
                flags={"required": True},
            )

            origin = cls._schema_on_200.value.Element.origin
            origin.added_by = AAZStrType(
                serialized_name="addedBy",
                flags={"required": True},
            )
            origin.added_by_type = AAZStrType(
                serialized_name="addedByType",
                flags={"required": True},
            )

            return cls._schema_on_200


class _AddOrUpdateAlertHelper:
    """Helper class for AddOrUpdateAlert"""


__all__ = ["AddOrUpdateAlert"]
