pull_request:
  azure_pipeline:
    allow_list:
      - "wangzein007-azure-cli"
    disallow_job_list: []
    result_path: /test_results/
  comment:
    level_keys:
      - "Module"
      - "Profile"
      - "PythonVersion"