name: azure-cli
summary: Microsoft Azure CLI
description: |
 A great cloud needs great tools; we're excited to introduce Azure CLI, our
 next generation multi-platform command line experience for Azure.
confinement: strict
grade: stable
base: core22
adopt-info: azure-cli

apps:
  az:
    command: bin/python3 $SNAP/bin/az
    completer: az.snap.completion
    plugs:
      - network
      - home

parts:
  azure-cli:
    plugin: python
    source: .
    python-packages:
      - './src/azure-cli-core'
      - './src/azure-cli'
    python-requirements:
      - './src/azure-cli/requirements.py3.Linux.txt'
    override-build: |
      craftctl default
      cp $SNAPCRAFT_PART_BUILD/build_scripts/snap/az.snap.completion $SNAPCRAFT_PART_INSTALL/

      craftctl set version="$(git describe --tags --abbrev=0 | cut -d'-' -f3)"
