jobs:
- job: LiveTestPython38
  displayName: Live Test Python 3.8
  timeoutInMinutes: 999
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        addToPath: true
        architecture: 'x64'
    - bash: |
        cd ..
        pwd
        ls
        git clone https://github.com/Azure/azure-cli.git
        python -m venv env
        source env/bin/activate
        pip install azdev
        azdev setup -c
        azdev test vm
