# Some content of this file is generated.

trigger:
  branches:
    exclude:
    - '*'

schedules:
- cron: "0 18 * * 5"
  displayName: Weekly Friday test
  branches:
    include:
    - CLITest
  always: true

jobs:
- job: LiveTestPython38
  displayName: Live Test Python 3.8
  timeoutInMinutes: 9999
  strategy:
    maxParallel: 20
    matrix:
    
      dms:
        Target: dms
    
      advisor:
        Target: advisor
    
      netappfiles:
        Target: netappfiles
    
      consumption:
        Target: consumption
    
      batchai:
        Target: batchai
    
      relay:
        Target: relay
    
      security:
        Target: security
    
      vm:
        Target: vm
    
      lab:
        Target: lab
    
      role:
        Target: role
    
      maps:
        Target: maps
    
      policyinsights:
        Target: policyinsights
    
      profile:
        Target: profile
    
      rdbms:
        Target: rdbms
    
      iotcentral:
        Target: iotcentral
    
      sql:
        Target: sql
    
      eventhubs:
        Target: eventhubs
    
      deploymentmanager:
        Target: deploymentmanager
    
      storage:
        Target: storage
    
      cloud:
        Target: cloud
    
      find:
        Target: find
    
      configure:
        Target: configure
    
      privatedns:
        Target: privatedns
    
      extension:
        Target: extension
    
      hdinsight:
        Target: hdinsight
    
      keyvault:
        Target: keyvault
    
      acr:
        Target: acr
    
      network:
        Target: network
    
      appconfig:
        Target: appconfig
    
      aro:
        Target: aro
    
      resource:
        Target: resource
    
      cognitiveservices:
        Target: cognitiveservices
    
      ams:
        Target: ams
    
      monitor:
        Target: monitor
    
      natgateway:
        Target: natgateway
    
      servicebus:
        Target: servicebus
    
      dls:
        Target: dls
    
      util:
        Target: util
    
      servicefabric:
        Target: servicefabric
    
      cdn:
        Target: cdn
    
      interactive:
        Target: interactive
    
      eventgrid:
        Target: eventgrid
    
      iot:
        Target: iot
    
      batch:
        Target: batch
    
      acs:
        Target: acs
    
      cosmosdb:
        Target: cosmosdb
    
      billing:
        Target: billing
    
      reservations:
        Target: reservations
    
      apim:
        Target: apim
    
      backup:
        Target: backup
    
      appservice:
        Target: appservice
    
      managedservices:
        Target: managedservices
    
      sqlvm:
        Target: sqlvm
    
      botservice:
        Target: botservice
    
      dla:
        Target: dla
    
      kusto:
        Target: kusto
    
      redis:
        Target: redis
    
      feedback:
        Target: feedback
    
      container:
        Target: container
    
      search:
        Target: search
    
      signalr:
        Target: signalr
    
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        addToPath: true
        architecture: 'x64'
    - bash: |
        if [[ "$(USER_TARGET)" =~ "$(Target)" || "$(USER_TARGET)" == "" ]]; then
          echo "Match!"
        else
          echo "Not match!"
          exit
        fi
        cd ..
        pwd
        ls
        git clone -b $(USER_BRANCH) $(USER_REPO)
        #git clone https://github.com/Azure/azure-cli-extensions.git
        python -m venv env
        source env/bin/activate
        pip install azdev
        azdev setup -c azure-cli
        az login --service-principal --username $(APP_ID) --password $(PASSWORD) --tenant $(TENANT_ID)
        azdev test $(Target) $(USER_LIVE) --no-exitfirst -a "-n 8"
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '/home/vsts/.azdev/env_config/home/vsts/work/1/env/test_results.xml'
        testRunTitle: 'Azure CLI live test results of $(Target)'
        # mergeTestResults: true
        # testResultsFormat: 'JUnit'

- job: SendEmail
  displayName: Send email
  dependsOn: LiveTestPython38
  condition: succeededOrFailed()
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        addToPath: true
        architecture: 'x64'
    - bash: |
        pwd
        # Send notification when target is all.
        if [[ "$(USER_TARGET)" == "" ]]; then
          commit_id=`git ls-remote https://github.com/Azure/azure-cli.git HEAD`
          pip install sendgrid
          python /home/vsts/work/1/s/scripts/live_test/sendemail.py $(SENDGRID_KEY) $(Build.BuildId) $(USER_REPO) $(USER_BRANCH)
        fi