FROM ubuntu:14.04
RUN apt-get update -qq
# install *-dev packages below so cryptography package can install
RUN apt-get install -qqy python-pip curl libssl-dev libffi-dev python-dev
ENV AZURE_CLI_DISABLE_PROMPTS 1
RUN curl http://azure-cli-nightly.westus.cloudapp.azure.com/install | bash
CMD az
