#pylint: skip-file
# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DeploymentPublicIp(Model):
    """
    Deployment operation parameters.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :param allocation_method: IP address Allocation method. Possible values
     include: 'Dynamic', 'Static'. Default value: "Dynamic" .
    :type allocation_method: str
    :param name: Name of the Public IP address.
    :type name: str
    :ivar _artifacts_location: Container URI of of the template. Default
     value:
     "https://azuresdkci.blob.core.windows.net/templatehost/CreatePublicIp_2016-06-06"
     .
    :vartype _artifacts_location: str
    :param location: Location (e.g. eastus).
    :type location: str
    :param dns_name: Globally unique DNS entry.
    :type dns_name: str
    :param public_ip_address_type: Whether to include a DNS entry or not.
     Possible values include: 'dns', 'noDns'. Default value: "noDns" .
    :type public_ip_address_type: str
    :param content_version: If included it must match the ContentVersion in
     the template.
    :type content_version: str
    :ivar uri: URI referencing the template. Default value:
     "https://azuresdkci.blob.core.windows.net/templatehost/CreatePublicIp_2016-06-06/azuredeploy.json"
     .
    :vartype uri: str
    :ivar mode: Gets or sets the deployment mode. Default value:
     "Incremental" .
    :vartype mode: str
    """ 

    _validation = {
        'name': {'required': True},
        '_artifacts_location': {'required': True, 'constant': True},
        'uri': {'required': True, 'constant': True},
        'mode': {'required': True, 'constant': True},
    }

    _attribute_map = {
        'allocation_method': {'key': 'parameters.allocationMethod.value', 'type': 'str'},
        'name': {'key': 'parameters.name.value', 'type': 'str'},
        '_artifacts_location': {'key': 'parameters._artifactsLocation.value', 'type': 'str'},
        'location': {'key': 'parameters.location.value', 'type': 'str'},
        'dns_name': {'key': 'parameters.dnsName.value', 'type': 'str'},
        'public_ip_address_type': {'key': 'parameters.publicIpAddressType.value', 'type': 'str'},
        'content_version': {'key': 'templateLink.contentVersion', 'type': 'str'},
        'uri': {'key': 'templateLink.uri', 'type': 'str'},
        'mode': {'key': 'properties.mode', 'type': 'str'},
    }

    _artifacts_location = "https://azuresdkci.blob.core.windows.net/templatehost/CreatePublicIp_2016-06-06"

    uri = "https://azuresdkci.blob.core.windows.net/templatehost/CreatePublicIp_2016-06-06/azuredeploy.json"

    mode = "Incremental"

    def __init__(self, name, allocation_method="Dynamic", location=None, dns_name=None, public_ip_address_type="noDns", content_version=None):
        self.allocation_method = allocation_method
        self.name = name
        self.location = location
        self.dns_name = dns_name
        self.public_ip_address_type = public_ip_address_type
        self.content_version = content_version
