jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/postgresql@v1
        with:
          server-name: POSTGRESQL_SERVER_NAME
          connection-string: POSTGRESQL_CONNECTION_STRING
          plsql-file: POSTGRESQL_FILE_NAME
