[project]
name = "aaz-flow"
version = "0.1.0"
description = "The MCP server utilized for code generation in Azure CLI (AAZ)."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.12.0",
]
