# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "eventhubs eventhub fabric-shortcut create",
)
class Create(AAZCommand):
    """Create a Microsoft Fabric shortcut.

    :example: Create or update a Fabric shortcut
        az eventhubs eventhub fabric-shortcut create --resource-group contoso-rg --namespace-name contoso-eventhub --event-hub-name orders --fabric-shortcut-name orders-shortcut --configuration "{artifact-id:33333333-3333-3333-3333-333333333333,artifact-name:orders-eventstream,premium-capacity-id:44444444-4444-4444-4444-444444444444,tenant-id:11111111-1111-1111-1111-111111111111,workspace-id:22222222-2222-2222-2222-222222222222,workspace-name:contoso-workspace}" --shortcut-status Pending --shortcut-type Entity
    """

    _aaz_info = {
        "version": "2026-07-01-preview",
        "resources": [
            ["mgmt-plane", "/subscriptions/{}/resourcegroups/{}/providers/microsoft.eventhub/namespaces/{}/eventhubs/{}/fabricshortcuts/{}", "2026-07-01-preview"],
        ]
    }

    def _handler(self, command_args):
        super()._handler(command_args)
        self._execute_operations()
        return self._output()

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.event_hub_name = AAZStrArg(
            options=["--event-hub-name"],
            help="The Event Hub name",
            required=True,
            fmt=AAZStrArgFormat(
                max_length=256,
                min_length=1,
            ),
        )
        _args_schema.fabric_shortcut_name = AAZStrArg(
            options=["-n", "--name", "--fabric-shortcut-name"],
            help="The Microsoft Fabric shortcut name.",
            required=True,
            fmt=AAZStrArgFormat(
                pattern="^.+$",
            ),
        )
        _args_schema.namespace_name = AAZStrArg(
            options=["--namespace-name"],
            help="The Namespace name",
            required=True,
            fmt=AAZStrArgFormat(
                pattern="^[a-zA-Z][a-zA-Z0-9-]{6,50}[a-zA-Z0-9]$",
                max_length=50,
                min_length=6,
            ),
        )
        _args_schema.resource_group = AAZResourceGroupNameArg(
            required=True,
        )

        # define Arg Group "Properties"

        _args_schema = cls._args_schema
        _args_schema.configuration = AAZObjectArg(
            options=["--configuration"],
            arg_group="Properties",
            help="Microsoft Fabric workspace and artifact configuration.",
        )
        _args_schema.shortcut_status = AAZStrArg(
            options=["--shortcut-status"],
            arg_group="Properties",
            help="The current shortcut status. Only Pending can be supplied on create or update.",
            enum={"Approved": "Approved", "Pending": "Pending", "Rejected": "Rejected"},
        )
        _args_schema.shortcut_type = AAZStrArg(
            options=["--shortcut-type"],
            arg_group="Properties",
            help="The type of the shortcut.",
            enum={"Entity": "Entity", "Network": "Network"},
        )

        configuration = cls._args_schema.configuration
        configuration.artifact_id = AAZUuidArg(
            options=["artifact-id"],
            help="The Microsoft Fabric artifact ID.",
            required=True,
        )
        configuration.artifact_name = AAZStrArg(
            options=["artifact-name"],
            help="The Microsoft Fabric artifact name.",
        )
        configuration.log_analytics_resource_id = AAZResourceIdArg(
            options=["log-analytics-resource-id"],
            help="The resource ID of the Log Analytics workspace.",
        )
        configuration.premium_capacity_id = AAZStrArg(
            options=["premium-capacity-id"],
            help="The Microsoft Fabric premium capacity ID.",
        )
        configuration.tenant_id = AAZUuidArg(
            options=["tenant-id"],
            help="The Microsoft Fabric tenant ID.",
            required=True,
        )
        configuration.workspace_id = AAZUuidArg(
            options=["workspace-id"],
            help="The Microsoft Fabric workspace ID.",
            required=True,
        )
        configuration.workspace_name = AAZStrArg(
            options=["workspace-name"],
            help="The Microsoft Fabric workspace name.",
        )
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        self.FabricShortcutsCreateOrUpdate(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class FabricShortcutsCreateOrUpdate(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200]:
                return self.on_200(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.EventHub/namespaces/{namespaceName}/eventhubs/{eventHubName}/fabricShortcuts/{fabricShortcutName}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "PUT"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "eventHubName", self.ctx.args.event_hub_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "fabricShortcutName", self.ctx.args.fabric_shortcut_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "namespaceName", self.ctx.args.namespace_name,
                    required=True,
                ),
                **self.serialize_url_param(
                    "resourceGroupName", self.ctx.args.resource_group,
                    required=True,
                ),
                **self.serialize_url_param(
                    "subscriptionId", self.ctx.subscription_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "api-version", "2026-07-01-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Content-Type", "application/json",
                ),
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        @property
        def content(self):
            _content_value, _builder = self.new_content_builder(
                self.ctx.args,
                typ=AAZObjectType,
                typ_kwargs={"flags": {"required": True, "client_flatten": True}}
            )
            _builder.set_prop("properties", AAZObjectType)

            properties = _builder.get(".properties")
            if properties is not None:
                properties.set_prop("configuration", AAZObjectType, ".configuration", typ_kwargs={"flags": {"required": True}})
                properties.set_prop("shortcutStatus", AAZStrType, ".shortcut_status")
                properties.set_prop("shortcutType", AAZStrType, ".shortcut_type")

            configuration = _builder.get(".properties.configuration")
            if configuration is not None:
                configuration.set_prop("artifactId", AAZStrType, ".artifact_id", typ_kwargs={"flags": {"required": True}})
                configuration.set_prop("artifactName", AAZStrType, ".artifact_name")
                configuration.set_prop("logAnalyticsResourceId", AAZStrType, ".log_analytics_resource_id")
                configuration.set_prop("premiumCapacityId", AAZStrType, ".premium_capacity_id")
                configuration.set_prop("tenantId", AAZStrType, ".tenant_id", typ_kwargs={"flags": {"required": True}})
                configuration.set_prop("workspaceId", AAZStrType, ".workspace_id", typ_kwargs={"flags": {"required": True}})
                configuration.set_prop("workspaceName", AAZStrType, ".workspace_name")

            return self.serialize_content(_content_value)

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZObjectType()

            _schema_on_200 = cls._schema_on_200
            _schema_on_200.id = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200.location = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200.name = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200.properties = AAZObjectType()
            _schema_on_200.system_data = AAZObjectType(
                serialized_name="systemData",
                flags={"read_only": True},
            )
            _schema_on_200.type = AAZStrType(
                flags={"read_only": True},
            )

            properties = cls._schema_on_200.properties
            properties.configuration = AAZObjectType(
                flags={"required": True},
            )
            properties.created_at = AAZStrType(
                serialized_name="createdAt",
                flags={"read_only": True},
            )
            properties.modified_at = AAZStrType(
                serialized_name="modifiedAt",
                flags={"read_only": True},
            )
            properties.shortcut_status = AAZStrType(
                serialized_name="shortcutStatus",
            )
            properties.shortcut_type = AAZStrType(
                serialized_name="shortcutType",
            )
            properties.status_description = AAZStrType(
                serialized_name="statusDescription",
                flags={"read_only": True},
            )

            configuration = cls._schema_on_200.properties.configuration
            configuration.artifact_id = AAZStrType(
                serialized_name="artifactId",
                flags={"required": True},
            )
            configuration.artifact_name = AAZStrType(
                serialized_name="artifactName",
            )
            configuration.log_analytics_resource_id = AAZStrType(
                serialized_name="logAnalyticsResourceId",
            )
            configuration.premium_capacity_id = AAZStrType(
                serialized_name="premiumCapacityId",
            )
            configuration.tenant_id = AAZStrType(
                serialized_name="tenantId",
                flags={"required": True},
            )
            configuration.workspace_id = AAZStrType(
                serialized_name="workspaceId",
                flags={"required": True},
            )
            configuration.workspace_name = AAZStrType(
                serialized_name="workspaceName",
            )

            system_data = cls._schema_on_200.system_data
            system_data.created_at = AAZStrType(
                serialized_name="createdAt",
            )
            system_data.created_by = AAZStrType(
                serialized_name="createdBy",
            )
            system_data.created_by_type = AAZStrType(
                serialized_name="createdByType",
            )
            system_data.last_modified_at = AAZStrType(
                serialized_name="lastModifiedAt",
            )
            system_data.last_modified_by = AAZStrType(
                serialized_name="lastModifiedBy",
            )
            system_data.last_modified_by_type = AAZStrType(
                serialized_name="lastModifiedByType",
            )

            return cls._schema_on_200


class _CreateHelper:
    """Helper class for Create"""


__all__ = ["Create"]
