FROM python:3.6-slim-jessie

LABEL a01.product="azurecli"
LABEL a01.index.schema="v2"

COPY build /tmp/build
COPY docker_app /app

RUN pip install -r /app/requirements.txt && \
    find /tmp/build -name '*.whl' | xargs pip install && \
    rm -rf /tmp/build && \
    python /app/collect_tests.py > /app/test_index && \
    rm /app/collect_tests.py && \
    rm /app/requirements.txt && \
    rm -rf ~/.cache/pip

