#!D:\second-azure-cli\azure-cli\env38\Scripts\python.exe
# EASY-INSTALL-DEV-SCRIPT: 'azure-cli==2.10.0','az'
__requires__ = 'azure-cli==2.10.0'
__import__('pkg_resources').require('azure-cli==2.10.0')
__file__ = 'D:\\second-azure-cli\\azure-cli\\src\\azure-cli\\az'
with open(__file__) as f:
    exec(compile(f.read(), __file__, 'exec'))
