#!D:\second-azure-cli\azure-cli\env2\Scripts\python.exe
# EASY-INSTALL-DEV-SCRIPT: 'azure-cli==2.9.1','az'
__requires__ = 'azure-cli==2.9.1'
__import__('pkg_resources').require('azure-cli==2.9.1')
__file__ = 'D:\\second-azure-cli\\azure-cli\\src\\azure-cli\\az'
with open(__file__) as f:
    exec(compile(f.read(), __file__, 'exec'))
