parameters:
- name: architectures
  type: object
- name: downloadArtifactNamePrefix
  type: string
  default: 'docker-azurelinux3.0'
- name: downloadArtifactNameSuffix
  type: string
  default: ''
- name: ShouldTest
  type: boolean
  default: false
- name: timeoutInMinutes
  type: number
  default: 180
- name: AzCliVersion
  type: string
  default: ''
- name: AzCliImageName
  type: string
  default: ''
- name: AzCliImageTag
  type: string
  default: ''

jobs:
- job: TestDockerImageUnitTest
  displayName: Unit Test - Docker
  condition: and(succeeded(), eq(${{parameters.ShouldTest}}, true))
  timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
  strategy:
    matrix:
      ${{ each arch in parameters.architectures }}:
        ${{ arch.name }}:
          pool: ${{ arch.pool }}
          downloadArtifactName: ${{ parameters.AzCliVersion }}-docker-${{ arch.value }}${{ parameters.downloadArtifactNameSuffix }}
  pool:
    name: $(pool)
  steps:
  - task: DownloadPipelineArtifact@1
    displayName: 'Download Docker Image'
    inputs:
      TargetPath: '$(Build.ArtifactStagingDirectory)/docker'
      artifactName: $(downloadArtifactName)

  - bash: ./scripts/ci/install_docker.sh
    displayName: Install Docker

  - bash: |
      set -exv
      
      echo "== Load docker image =="
      TAR_FILE="$SYSTEM_ARTIFACTSDIRECTORY/docker/docker-azure-cli-${{ parameters.AzCliVersion }}.tar"
      docker load < $TAR_FILE
      
      echo "== Run az self-test  =="
      docker run ${{ parameters.AzCliImageName }}:${{ parameters.AzCliImageTag }} /bin/bash -c "time az self-test && time az --version && tdnf list --installed"
    displayName: '🚀 Self Test'

  - bash: |
      echo "== List docker image =="
      docker images
      
      echo "== Run unit test =="
      docker run --rm -v $(pwd):/azure-cli ${{ parameters.AzCliImageName }}:${{ parameters.AzCliImageTag }} /bin/bash /azure-cli/scripts/release/rpm/test_azurelinux_in_docker.sh --InstallRPM false
    displayName: '🚀🚀 Unit Test'
