parameters:
- name: architectures
  type: object
- name: downloadArtifactNamePrefix
  type: string
  default: 'docker-azurelinux3.0'
- name: downloadArtifactNameSuffix
  type: string
  default: ''
- name: ShouldTest
  displayName: Test?
  type: boolean
  default: false
- name: timeoutInMinutes
  type: number
  default: 100
- name: AzCliVersion
  type: string
  default: ''
- name: AzCliImageName
  type: string
  default: ''
- name: AzCliImageTag
  type: string
  default: ''
- name: TestAzUserId
  type: string
  default: ''
- name: TestAzSubscription
  type: string
  default: ''
- name: TestAzTenant
  type: string
  default: ''
- name: TestServiceConnectionId
  type: string
  default: ''

jobs:
- job: TestDockerImageSmokeTest
  displayName: Test Docker Image - Smoke Test
  condition: and(succeeded(), eq(${{parameters.ShouldTest}}, true))
  timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
  strategy:
    matrix:
      ${{ each arch in parameters.architectures }}:
        ${{ arch.name }}:
          pool: ${{ arch.pool }}
          downloadArtifactName: ${{ parameters.downloadArtifactNamePrefix }}-${{ arch.value }}${{ parameters.downloadArtifactNameSuffix }}
          architecture: ${{ arch.value }}
  pool:
    name: $(pool)
  steps:
    - task: DownloadPipelineArtifact@1
      displayName: 'Download Docker Image'
      inputs:
        TargetPath: '$(Build.ArtifactStagingDirectory)/docker'
        artifactName: $(downloadArtifactName)

    - bash: ./scripts/ci/install_docker.sh
      displayName: Install Docker

    - task: Bash@3
      displayName: Prepare Test and Output Folders
      inputs:
        targetType: 'inline'
        script: |
          mkdir output
          chmod +x ./scripts/release/docker/test_az_cli_in_pipeline.sh
          ls ./.azure-pipelines

    - task: Bash@3
      displayName: 🚀 Self Test
      inputs:
        targetType: 'inline'
        script: |
          echo "== Load docker image =="
          TAR_FILE="$SYSTEM_ARTIFACTSDIRECTORY/docker/docker-azure-cli-${{ parameters.AzCliVersion }}.tar"
          docker load < $TAR_FILE

          echo "== Docker Images =="
          docker images
          
          echo "== Run az self-test  =="
          docker run ${{ parameters.AzCliImageName }}:${{ parameters.AzCliImageTag }} /bin/bash -c "time az self-test && time az --version && tdnf list --installed"

          #sudo docker run $(TestImage):$(TestImageTag) /bin/bash -c "time az self-test && time az --version && (tdnf list --installed || true) "

    - task: Bash@3
      displayName: 🚀🚀 Smoke Test
      inputs:
        targetType: 'inline'
        script: |
          scUrl="${SYSTEM_OIDCREQUESTURI}?api-version=7.1&serviceConnectionId=${{parameters.TestServiceConnectionId}}"
          response=$(curl -s -X POST "$scUrl" -H "Authorization: Bearer $(System.AccessToken)" -H "Content-Type: application/json" -d '')
          OidcToken=$(echo "$response" | jq -r '.oidcToken')

          sudo docker run -v $(System.DefaultWorkingDirectory)/scripts/docker:/test ${{ parameters.AzCliImageName }}:${{ parameters.AzCliImageTag }} /bin/bash -c "az login --service-principal --username ${{parameters.TestAzUserId}} --tenant ${{parameters.TestAzTenant}} --federated-token $OidcToken && az account set --subscription ${{parameters.TestAzSubscription}} && /test/test_az_cli_in_pipeline.sh"

          echo "--------------------------------------------"

          mv $(System.DefaultWorkingDirectory)/scripts/docker/azure_cli_test_output.log $(System.DefaultWorkingDirectory)/output/azure_cli_test_output_before.log
          mv $(System.DefaultWorkingDirectory)/scripts/docker/azure_cli_test_result.csv $(System.DefaultWorkingDirectory)/output/azure_cli_test_result_before.csv
          ls $(System.DefaultWorkingDirectory)/output

    - publish: $(System.DefaultWorkingDirectory)/output
      artifact: ${{ parameters.AzCliVersion }}-$(architecture)-smoke-test
      displayName: Publish Artifact
