parameters:
- name: architectures
  type: object
- name: downloadArtifactNamePrefix
  type: string
  default: 'docker-azurelinux3.0'
- name: downloadArtifactNameSuffix
  type: string
  default: ''
- name: ShouldTest
  displayName: Test?
  type: boolean
  default: false
- name: timeoutInMinutes
  type: number
  default: 180
- name: AzCliVersion
  type: string
  default: ''
- name: AzCliImageName
  type: string
  default: ''
- name: AzCliImageTag
  type: string
  default: ''

jobs:
- job: TestDockerImageUnitTest
  displayName: Test Docker Image - Unit Test
  condition: and(succeeded(), eq(${{parameters.ShouldTest}}, true))
  timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
  strategy:
    matrix:
      ${{ each arch in parameters.architectures }}:
        ${{ arch.name }}:
          pool: ${{ arch.pool }}
          downloadArtifactName: ${{ parameters.downloadArtifactNamePrefix }}-${{ arch.value }}${{ parameters.downloadArtifactNameSuffix }}
  pool:
    name: $(pool)
  steps:
    - task: DownloadPipelineArtifact@1
      displayName: 'Download Docker Image'
      inputs:
        TargetPath: '$(Build.ArtifactStagingDirectory)/docker'
        artifactName: $(downloadArtifactName)

    - bash: ./scripts/ci/install_docker.sh
      displayName: Install Docker

    - task: Bash@3
      displayName: Create Test and Output Folders
      inputs:
        targetType: 'inline'
        script: |
          mkdir output
          chmod +x ./scripts/release/docker/test_az_cli_in_pipeline.sh
          ls ./.azure-pipelines

    - bash: |
        set -exv

        echo "== Load docker image =="
        TAR_FILE="$SYSTEM_ARTIFACTSDIRECTORY/docker/docker-azure-cli-${{ parameters.AzCliVersion }}.tar"
        docker load < $TAR_FILE
        
        echo "== Run az self-test  =="
        docker run ${{ parameters.AzCliImageName }}:${{ parameters.AzCliImageTag }} /bin/bash -c "time az self-test && time az --version && tdnf list --installed"
        
      displayName: 'Run Simple Test'

    - bash: |
        echo "== List docker image =="
        docker images
        
        echo "== Run unit test =="
        docker run --rm -e AZ_INSTALLER='' -v $(pwd):/azure-cli ${{ parameters.AzCliImageName }}:${{ parameters.AzCliImageTag }} /bin/bash /azure-cli/scripts/release/rpm/test_azurelinux_in_docker.sh --InstallRPM false
        
      displayName: 'Run Unit Test'
