name: "[Microsoft Internal / Service Team] Feature Request"
description: Use this template to create a feature request for microsoft internal or service team
labels: ["feature-request"]
body:
  - type: markdown
    id: example
    attributes:
      value: |
        [How to Request a Feature in CLI](https://github.com/Azure/azure-cli/blob/dev/doc/how_to_request_a_feature_in_cli.md)
        [A Great Example](https://github.com/Azure/azure-cli/issues/22275)
  - type: textarea
    id: command
    attributes:
      label: Related command
      description: Please provide the related commands and parameters with az {command} if you can, so that we can quickly route to the related team for help.
      placeholder: e.g., `az vm create --image`
    validations:
      required: false
  - type: input
    id: provider
    attributes:
      label: Resource Provider
      description: What is the Azure resource provider your feature is part of?\nIf you cannot provide, please fill in N/A.
      placeholder: e.g., Microsoft.Compute/disks
    validations:
      required: true
  - type: textarea
    id: feature-desc
    attributes:
      label: Description of Feature or Work Requested
      description: Provide a brief description of the feature or problem. A link to conceptual documentation may be helpful too.\nIf you cannot provide, please fill in N/A.
      placeholder:
      value:
    validations:
      required: true
  - type: input
    id: mini-api
    attributes:
      label: Minimum API Version Required
      description: What is the minimum API version of your service required to implement your feature?\nIf you cannot provide, please fill in N/A.
      placeholder: e.g., 2021-04-01
    validations:
      required: true
  - type: textarea
    id: swagger
    attributes:
      label: Swagger PR link / SDK link
      description: Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the master branch of the REST API specs repo.\nIf you cannot provide, please fill in N/A.
      placeholder: e.g., https://github.com/Azure/azure-rest-api-specs/pull/16629
    validations:
      required: true
  - type: textarea
    id: request-example
    attributes:
      label: Request Example
      description: Provide example files which include the request body and response body of REST service.
      placeholder: e.g., https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/stable/2022-03-01/ComputeRP/examples/virtualMachineExamples/VirtualMachine_Create_CustomImageVmFromAnUnmanagedGeneralizedOsImage.json
    validations:
      required: false
  - type: input
    id: date
    attributes:
      label: Target Date
      description: If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates, it will help us prioritize your request against other requests.
      placeholder: e.g., 2022-07-05
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the feature.
      placeholder:
      value:
    validations:
      required: false
