name: "[Microsoft Internal / Service Team] Feature Request"
description: Use this template to create a feature request for microsoft internal or service team
labels: ["feature-request"]
body:
  - type: markdown
    id: example
    attributes:
      value: |
        [How to Request a Feature in CLI](https://github.com/Azure/azure-cli/blob/dev/doc/how_to_request_a_feature_in_cli.md)
        [A Great Example](https://github.com/Azure/azure-cli/issues/22275)
  - type: checkboxes
    id: checklist
    attributes:
      label: Preconditions
      description: |
        If the commands relies on Python SDK and requires upgrading the api-version, please ensure that the Python SDK is ready. 
        You can refer to the documents below to release a new version of the Python SDK:
        - https://github.com/Azure/azure-rest-api-specs/wiki/Abstract-about-how-to-ask-for-public-SDK-release
        - https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/release-request/rules-for-release-request.md
        
        **But it's not required for the commands generated by our advanced code generation tool [CodeGen - AAZ](https://azure.github.io/aaz-dev-tools/) (Code Gen V2).**
        This tool is easy to use and can bring you the following benefits:
        - It can improve your development efficiency and reduce manual effort.
        - It can ensure the style and consistency of code, so it also reduces the burden of PR review.
        - It can improve code quality and reduce the occurrence of bugs.
        ......
        If you are interested in it and would like to learn more, please get support via [azure-cli-codegen-channel](https://aka.ms/azure-cli-codegen-channel).
      options:
        - label: No need to upgrade Python SDK or the Python SDK is ready.
          required: true
  - type: textarea
    id: command
    attributes:
      label: Related command
      description: Please provide the related commands and parameters with az {command} if you can, so that we can quickly route to the related team for help.
      placeholder: e.g., `az vm create --image`
    validations:
      required: false
  - type: input
    id: provider
    attributes:
      label: Resource Provider
      description: |
        What is the Azure resource provider your feature is part of?
        If you cannot provide, please fill in N/A.
      placeholder: e.g., Microsoft.Compute/disks
    validations:
      required: true
  - type: textarea
    id: feature-desc
    attributes:
      label: Description of Feature or Work Requested
      description: |
        Provide a brief description of the feature. A link to conceptual documentation may be helpful too.
        If you cannot provide, please fill in N/A.
      placeholder:
      value:
    validations:
      required: true
  - type: input
    id: mini-api
    attributes:
      label: Minimum API Version Required
      description: |
        What is the minimum API version of your service required to support your feature?
        If you cannot provide, please fill in N/A.
      placeholder: e.g., 2021-04-01
    validations:
      required: true
  - type: textarea
    id: swagger
    attributes:
      label: Swagger PR link / SDK link
      description: |
        Provide a link to the location of your feature(s) in the REST API specs repo. If your feature(s) has corresponding commit or pull request in the REST API specs repo, provide them. This should be on the main branch of the REST API specs repo.
        If you cannot provide, please fill in N/A.
      placeholder: e.g., https://github.com/Azure/azure-rest-api-specs/pull/16629
    validations:
      required: true
  - type: textarea
    id: request-example
    attributes:
      label: Request Example
      description: Provide example files which include the request body and response body of REST service.
      placeholder: e.g., https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/stable/2022-03-01/ComputeRP/examples/virtualMachineExamples/VirtualMachine_Create_CustomImageVmFromAnUnmanagedGeneralizedOsImage.json
    validations:
      required: false
  - type: input
    id: date
    attributes:
      label: Target Date
      description: If you have a target date for release of this feature/work, please provide it. While we can't guarantee these dates, it will help us prioritize your request against other requests.
      placeholder: e.g., 2022-07-05
    validations:
      required: true
  - type: input
    id: pm
    attributes:
      label: PM Contact
      description: Please provide PM contact (Microsoft alias).
      placeholder: e.g., @pm
    validations:
      required: true
  - type: input
    id: engineer
    attributes:
      label: Engineer Contact
      description: Please provide Engineer contact (Microsoft alias).
      placeholder: e.g., @engineer
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the feature.
      placeholder:
      value:
    validations:
      required: false
