parameters: []

steps:
- bash: |
    set -euo pipefail

    if ! command -v brew >/dev/null 2>&1; then
      NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    echo "##vso[task.prependpath]/home/linuxbrew/.linuxbrew/bin"
    brew --version
  displayName: 'Install Linuxbrew'