#!/bin/bash
echo "azdev (/workspaces/azdev) and azcli (/workspaces/azure-cli) have been setup and configured."
echo "Extra manual config steps:"
echo "  - config vscode python interpreter to '/workspaces/azdev/bin/python'"
echo "  - run 'source /workspaces/azdev/bin/activate', so you have azdev venv loaded."
echo "==============="
echo "Debug:"
echo "  - modify .vscode/launch.json 'args' in 'Azure CLI Debug (Integrated Console)' with your own command in string array (not include az itself) "
echo "  - seems python extension won't close the debug session, you would have to watch a terminal tab 'Python Debug Console' for debug output."
echo ""
echo ""