# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

from azure.cli.core.commands.parameters import resource_group_name_type


def load_arguments(self, _):
    with self.argument_context(
        "disconnectedoperations edgemarketplace listoffers"
    ) as c:
        c.argument("resource_group_name", arg_type=resource_group_name_type)
        c.argument(
            "resource_name", type=str, help="Name of the resource to list offers for"
        )

    with self.argument_context("disconnectedoperations edgemarketplace getoffer") as c:
        c.argument("resource_group_name", arg_type=resource_group_name_type)
        c.argument(
            "resource_name", type=str, help="Name of the resource to list offers for"
        )
        c.argument("offer_id", type=str, help="Name of the offer")
        c.argument("publisher_name", type=str, help="Name of the publisher")

    with self.argument_context(
        "disconnectedoperations edgemarketplace packageoffer"
    ) as c:
        c.argument("resource_group_name", arg_type=resource_group_name_type)
        c.argument(
            "resource_name", type=str, help="Name of the resource to list offers for"
        )
        c.argument("publisher_name", type=str, help="Name of the publisher")
        c.argument("offer_id", type=str, help="Name of the offer to package")
        c.argument("sku", type=str, help="SKU of the product")
        c.argument("version", type=str, help="Version of the product")
        c.argument(
            "output_folder",
            type=str,
            help="Drive and directory to save the package to. Example: E:\\ or D:\\packages\\",
        )
        c.argument(
            "region",
            type=str,
            help="Azure region to use for marketplace access. If not specified, the current cloud's primary region will be used.",  # pylint: disable=line-too-long
            required=False,
        )
