name: GH Azdev Setup
description: 'azdev env setup'

runs:
  using: 'composite'
  steps:
    - name: Check Init GH Event
      env:
        action: ${{ toJSON(github.event.action) }}
        label: ${{ toJSON(github.event.label) }}
      shell: bash
      run: |
        echo start azdev env setup
    - name: Checkout CLI repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # checkout all branches
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}  # checkout pull request branch
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install azdev
      shell: bash
      run: | 
        python -m pip install --upgrade pip
        set -ev
        python -m venv env
        chmod +x env/bin/activate
        source ./env/bin/activate
        pip install azdev
        azdev --version
        cd ../
        azdev setup -c azure-cli --debug
        az --version
        pip list -v