#!/usr/bin/env python

import runpy
import sys
import os

dir = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'src')

if os.environ.get('PYTHONPATH') is None:
    os.environ['PYTHONPATH'] = dir
else:
    os.environ['PYTHONPATH'] = os.pathsep.join([
        dir,
        os.environ.get('PYTHONPATH'),
    ])

if os.environ.get('AZ_INSTALLER') is None:
    os.environ['AZ_INSTALLER'] = 'PIP'

if dir not in sys.path:
    sys.path.insert(0, dir)

runpy.run_module('azure.cli', run_name='__main__', alter_sys=True)
