#!/usr/bin/env python

import sys
import os

dir = os.path.dirname(os.path.realpath(__file__))

if os.environ.get('PYTHONPATH') == None:
    os.environ['PYTHONPATH'] = os.path.join(dir, 'src')
else:
    os.environ['PYTHONPATH'] = os.pathsep.join([
        os.path.join(dir, 'src'),
        os.environ.get('PYTHONPATH'),
    ])

os.execl(sys.executable, sys.executable , '-m', 'azure.cli', *sys.argv[1:])
