# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class LogValue(Model):
    """
    A log value set represents a set of log values in a time period.

    :param time: Gets or sets the time when the log was generated
    :type time: datetime
    :param resource_id: Gets or sets id of the reosurce related to the log.
    :type resource_id: str
    :param operation_name: Gets or sets the name of the operation.
    :type operation_name: str
    :param operation_version: Gets or sets the version of the operation.
    :type operation_version: str
    :param category: Gets or sets the category of the log.
    :type category: str
    :param result_type: Gets or sets the status of the operation.
    :type result_type: str
    :param result_signature: Gets or sets the substatus of the operation.
    :type result_signature: str
    :param result_description: Gets or sets the substatus of the operation.
    :type result_description: str
    :param duration_ms: Gets or sets the duration of the operation in
     milliseconds.
    :type duration_ms: int
    :param caller_ip_address: Gets or sets the caller IP address.
    :type caller_ip_address: str
    :param correlation_id: Gets or sets the correlation id of the log.  Used
     to group together a set of related log.
    :type correlation_id: str
    :param identity: Gets or sets the identity that generated the event.
    :type identity: str
    :param level: Gets or sets the level
     (Informational/Warning/Error/Critical) of the event.
    :type level: str
    :param location: Gets or sets tThe location of the resource emitting the
     event.
    :type location: str
    :param properties: Gets or sets the collection of extended properties.
    :type properties: dict
    """ 

    _attribute_map = {
        'time': {'key': 'time', 'type': 'iso-8601'},
        'resource_id': {'key': 'resourceId', 'type': 'str'},
        'operation_name': {'key': 'operationName', 'type': 'str'},
        'operation_version': {'key': 'operationVersion', 'type': 'str'},
        'category': {'key': 'category', 'type': 'str'},
        'result_type': {'key': 'resultType', 'type': 'str'},
        'result_signature': {'key': 'resultSignature', 'type': 'str'},
        'result_description': {'key': 'resultDescription', 'type': 'str'},
        'duration_ms': {'key': 'durationMs', 'type': 'int'},
        'caller_ip_address': {'key': 'callerIpAddress', 'type': 'str'},
        'correlation_id': {'key': 'correlationId', 'type': 'str'},
        'identity': {'key': 'identity', 'type': 'str'},
        'level': {'key': 'level', 'type': 'str'},
        'location': {'key': 'location', 'type': 'str'},
        'properties': {'key': 'properties', 'type': '{str}'},
    }

    def __init__(self, time=None, resource_id=None, operation_name=None, operation_version=None, category=None, result_type=None, result_signature=None, result_description=None, duration_ms=None, caller_ip_address=None, correlation_id=None, identity=None, level=None, location=None, properties=None):
        self.time = time
        self.resource_id = resource_id
        self.operation_name = operation_name
        self.operation_version = operation_version
        self.category = category
        self.result_type = result_type
        self.result_signature = result_signature
        self.result_description = result_description
        self.duration_ms = duration_ms
        self.caller_ip_address = caller_ip_address
        self.correlation_id = correlation_id
        self.identity = identity
        self.level = level
        self.location = location
        self.properties = properties
