# Some content of this file is generated.

name: CLI TEST RUN $(USER_TARGET) $(USER_LIVE) $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    exclude:
    - '*'

schedules:
- cron: "0 18 * * 5"
  displayName: Weekly Friday test
  branches:
    include:
    - CLITest
  always: true

jobs:
- job: LiveTestPython38
  displayName: Live Test Python 3.8
  timeoutInMinutes: 9999
  strategy:
    maxParallel: 20
    matrix:
      aro:
        Target: aro
      dla:
        Target: dla
      policyinsights:
        Target: policyinsights
      keyvault:
        Target: keyvault
      appservice:
        Target: appservice
      dls:
        Target: dls
      cosmosdb:
        Target: cosmosdb
      batchai:
        Target: batchai
      apim:
        Target: apim
      natgateway:
        Target: natgateway
      maps:
        Target: maps
      cognitiveservices:
        Target: cognitiveservices
      privatedns:
        Target: privatedns
      advisor:
        Target: advisor
      eventhubs:
        Target: eventhubs
      relay:
        Target: relay
      ams:
        Target: ams
      configure:
        Target: configure
      iot:
        Target: iot
      redis:
        Target: redis
      # interactive:
      #   Target: interactive
      search:
        Target: search
      cloud:
        Target: cloud
      reservations:
        Target: reservations
      backup:
        Target: backup
      rdbms:
        Target: rdbms
      appconfig:
        Target: appconfig
      resource:
        Target: resource
      billing:
        Target: billing
      acs:
        Target: acs
      signalr:
        Target: signalr
      profile:
        Target: profile
      storage:
        Target: storage
      deploymentmanager:
        Target: deploymentmanager
      lab:
        Target: lab
      vm:
        Target: vm
      util:
        Target: util
      consumption:
        Target: consumption
      netappfiles:
        Target: netappfiles
      network:
        Target: network
      iotcentral:
        Target: iotcentral
      managedservices:
        Target: managedservices
      acr:
        Target: acr
      kusto:
        Target: kusto
      servicefabric:
        Target: servicefabric
      find:
        Target: find
      dms:
        Target: dms
      sqlvm:
        Target: sqlvm
      cdn:
        Target: cdn
      botservice:
        Target: botservice
      container:
        Target: container
      monitor:
        Target: monitor
      batch:
        Target: batch
      security:
        Target: security
      feedback:
        Target: feedback
      sql:
        Target: sql
      servicebus:
        Target: servicebus
      hdinsight:
        Target: hdinsight
      role:
        Target: role
      extension:
        Target: extension
      eventgrid:
        Target: eventgrid
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        addToPath: true
        architecture: 'x64'
    - bash: |
        if [[ "$(USER_TARGET)" =~ "$(Target)" || "$(USER_TARGET)" == "" ]]; then
          echo "Match!"
        else
          echo "Not match!"
          exit
        fi
        cd ..
        pwd
        ls
        # ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
        git clone -b $(USER_BRANCH) $(USER_REPO)
        #git clone https://github.com/Azure/azure-cli-extensions.git
        python -m venv env
        source env/bin/activate
        # pip install azdev
        git clone https://github.com/Azure/azure-cli-dev-tools.git
        pip install -e azure-cli-dev-tools
        pip install pytest-json-report
        pip install pytest-html
        pip install pytest-rerunfailures
        azdev setup -c azure-cli
        # az login --service-principal --username $(APP_ID) --password $(PASSWORD) --tenant $(TENANT_ID)
        az login -u azureclitest@azuresdkteam.onmicrosoft.com -p $(AZURECLITESTPASSWORD)
        az account set -s 0b1f6471-1bf0-4dda-aec3-cb9272f09590
        # Sequential
        azdev test $(Target) $(USER_LIVE) --mark serial --xml-path test_results.sequential.xml --no-exitfirst -a "--json-report --json-report-summary --json-report-file=$(Target).report.sequential.json --html=$(Target).report.sequential.html --self-contained-html --reruns 3 -s"
        # Parallel
        azdev test $(Target) $(USER_LIVE) --mark "not serial" --xml-path test_results.parallel.xml --no-exitfirst -a "-n $(USER_PARALLELISM) --json-report --json-report-summary --json-report-file=$(Target).report.parallel.json --html=$(Target).report.parallel.html --self-contained-html --reruns 3 -s"
        pwd
        ls
      condition: or(containsValue(variables['USER_TARGET'], variables['Target']), eq(variables['USER_TARGET'], ''))
    - task: PublishTestResults@2
      # condition: succeededOrFailed()
      inputs:
        testResultsFiles: '/home/vsts/work/1/test_results.*.xml'
        testRunTitle: 'Azure CLI live test results of $(Target)'
        mergeTestResults: true
        # testResultsFormat: 'JUnit'
    - task: PublishBuildArtifacts@1
      # condition: succeededOrFailed()
      inputs:
        PathtoPublish: '/home/vsts/work/1/$(Target).report.sequential.json'
        ArtifactName: '$(Target).report.sequential.json'
        publishLocation: 'Container'
    - task: PublishBuildArtifacts@1
      # condition: succeededOrFailed()
      inputs:
        PathtoPublish: '/home/vsts/work/1/$(Target).report.sequential.html'
        ArtifactName: '$(Target).report.sequential.html'
        publishLocation: 'Container'
    - task: PublishBuildArtifacts@1
      # condition: succeededOrFailed()
      inputs:
        PathtoPublish: '/home/vsts/work/1/$(Target).report.parallel.json'
        ArtifactName: '$(Target).report.parallel.json'
        publishLocation: 'Container'
    - task: PublishBuildArtifacts@1
      # condition: succeededOrFailed()
      inputs:
        PathtoPublish: '/home/vsts/work/1/$(Target).report.parallel.html'
        ArtifactName: '$(Target).report.parallel.html'
        publishLocation: 'Container'

- job: SendEmail
  displayName: Send email
  dependsOn: LiveTestPython38
  condition: succeededOrFailed()
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        addToPath: true
        architecture: 'x64'
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'specific'
        downloadPath: '$(System.ArtifactsDirectory)'
    - bash: |
        echo $(System.ArtifactsDirectory)
        ls $(System.ArtifactsDirectory)
        pwd
        commit_id=`git ls-remote https://github.com/Azure/azure-cli.git HEAD`
        pip install sendgrid
        # Send notification
        az -v
        az login -u azureclitest@azuresdkteam.onmicrosoft.com -p $(AZURECLITESTPASSWORD)
        python /home/vsts/work/1/s/scripts/live_test/sendemail.py "$(SENDGRID_KEY)" "$(Build.BuildId)" "$(USER_REPO)" "$(USER_BRANCH)" "$(USER_TARGET)" "$(USER_LIVE)" "$(System.ArtifactsDirectory)" "$(Build.RequestedForEmail)" "$(ACCOUNT_KEY)"
        # python /home/vsts/work/1/s/scripts/live_test/upload.py "$(System.ArtifactsDirectory)" "$(ACCOUNT_KEY)" "$(USER_LIVE)"
        # Clean resources
        python /home/vsts/work/1/s/scripts/live_test/clean.py
#    - task: AzureCLI@2
#      inputs:
#        azureSubscription: 'AzureSDKTest(0b1f6471-1bf0-4dda-aec3-cb9272f09590)'
#        scriptType: 'bash'
#        scriptLocation: 'inlineScript'
#        inlineScript: |
#          az storage container create -n `date +%Y%m%d%H%M%S` --account-name clitestresultstac --account-key $(ACCOUNT_KEY)
#          #az storage blob upload -f -c -n