trigger:
  branches:
    exclude:
    - '*'

jobs:
- job: Gen
  displayName: Gen
  pool:
    vmImage: 'Ubuntu-16.04'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.8'
          addToPath: true
          architecture: 'x64'
      - bash: |
          cd ..
          git clone -b dev https://github.com/Azure/azure-cli.git
          git clone -b master https://github.com/Azure/azure-cli-extensions.git
          python /home/vsts/work/1/s/scripts/live_test/gen.py
          rm -rf azure-cli
          rm -rf azure-cli-extensions
          git clone -b CLITest https://username:password@github.com/username/repository.git
          cd azure-cli
          git push origin CLITest