#!/bin/bash

az batch --help
az batch account --help
az batch account login --help
az batch account list --help
az batch account show --help
az batch account create --help
az batch account set --help
az batch account delete --help
az batch account autostorage-keys --help
az batch account autostorage-keys sync --help
az batch account keys --help
az batch account keys list --help
az batch account keys renew --help

az batch application --help
az batch application list --help
az batch application show --help
az batch application create --help
az batch application set --help
az batch application delete --help
az batch application package --help
az batch application package create --help
az batch application package delete --help
az batch application package show --help
az batch application package list --help
az batch application package activate --help
az batch application summary --help
az batch application summary list --help
az batch application summary show --help

az batch location --help
az batch location quotas --help
az batch location quotas show --help

az batch certificate --help
az batch certificate create --help
az batch certificate delete --help
az batch certificate show --help
az batch certificate list --help

az batch pool --help
az batch pool create --help
az batch pool list --help
az batch pool delete --help
az batch pool show --help
az batch pool set --help
az batch pool reset --help
az batch pool resize --help
az batch pool node-agent-skus --help
az batch pool node-agent-skus list --help
az batch pool usage-metrics --help
az batch pool usage-metrics list --help
az batch pool all-statistics --help
az batch pool all-statistics show --help
az batch pool autoscale --help
az batch pool autoscale enable --help
az batch pool autoscale disable --help
az batch pool autoscale evaluate --help
az batch pool node-counts --help
az batch pool node-counts list --help

az batch node --help
az batch node delete --help
az batch node show --help
az batch node list --help
az batch node reboot --help
az batch node reimage --help
az batch node user --help
az batch node user create --help
az batch node user delete --help
az batch node user reset --help
az batch node scheduling --help
az batch node scheduling disable --help
az batch node scheduling enable --help
az batch node remote-login-settings --help
az batch node remote-login-settings show --help
az batch node remote-desktop --help
az batch node remote-desktop download --help
az batch node service-logs --help
az batch node service-logs upload --help
az batch node file --help
az batch node file delete --help
az batch node file download --help
az batch node file show --help
az batch node file list --help

az batch job --help
az batch job create --help
az batch job delete --help
az batch job show --help
az batch job set --help
az batch job reset --help
az batch job list --help
az batch job disable --help
az batch job enable --help
az batch job stop --help
az batch job all-statistics --help
az batch job all-statistics show --help
az batch job prep-release-status --help
az batch job prep-release-status list --help
az batch job task-counts --help
az batch job task-counts show --help

az batch job-schedule --help
az batch job-schedule create --help
az batch job-schedule delete --help
az batch job-schedule show --help
az batch job-schedule set --help
az batch job-schedule reset --help
az batch job-schedule disable --help
az batch job-schedule enable --help
az batch job-schedule stop --help
az batch job-schedule list --help

az batch task --help
az batch task create --help
az batch task list --help
az batch task delete --help
az batch task show --help
az batch task reset --help
az batch task reactivate --help
az batch task stop --help
az batch task subtask --help
az batch task subtask list --help
az batch task file --help
az batch task file delete --help
az batch task file download --help
az batch task file show --help
az batch task file list --help