# --------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
#
# Code generated by aaz-dev-tools
# --------------------------------------------------------------------------------------------

# pylint: skip-file
# flake8: noqa

from azure.cli.core.aaz import *


@register_command(
    "security va sql scans show",
    is_preview=True,
)
class Show(AAZCommand):
    """Get the scan details of a single scan record.

    :example: Show scan details for a given scan id on an Azure SQL database.
        az security va sql scans show --resource-id /subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Sql/servers/{server}/databases/{db} --scan-id Scan_2026-01-01T00-00-00Z

    :example: Show scan details on a SQL DB hosted on an Azure virtual machine.
        az security va sql scans show --resource-id /subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.Compute/virtualMachines/{vm} --database-name MyDb --scan-id Scan_2026-01-01T00-00-00Z
    """

    _aaz_info = {
        "version": "2026-04-01-preview",
        "resources": [
            ["mgmt-plane", "/{resourceid}/providers/microsoft.security/sqlvulnerabilityassessments/default/scans/{}", "2026-04-01-preview"],
        ]
    }

    def _handler(self, command_args):
        super()._handler(command_args)
        self._execute_operations()
        return self._output()

    _args_schema = None

    @classmethod
    def _build_arguments_schema(cls, *args, **kwargs):
        if cls._args_schema is not None:
            return cls._args_schema
        cls._args_schema = super()._build_arguments_schema(*args, **kwargs)

        # define Arg Group ""

        _args_schema = cls._args_schema
        _args_schema.resource_id = AAZStrArg(
            options=["--resource-id"],
            help="The fully qualified Azure Resource manager identifier of the resource.",
            required=True,
        )
        _args_schema.scan_id = AAZStrArg(
            options=["--scan-id"],
            help="The scan Id. Type 'latest' to get the scan record for the latest scan.",
            required=True,
        )
        _args_schema.database_name = AAZStrArg(
            options=["--database-name"],
            help="The name of the database to assess. Required when the API is called on the parent resource (e.g., server level) rather than on a specific database resource, since the database name is not part of the resource URI. This is the only way to assess system databases (e.g., master), which cannot be referenced directly in the resource URI.",
        )
        return cls._args_schema

    def _execute_operations(self):
        self.pre_operations()
        self.ScanV2sGet(ctx=self.ctx)()
        self.post_operations()

    @register_callback
    def pre_operations(self):
        pass

    @register_callback
    def post_operations(self):
        pass

    def _output(self, *args, **kwargs):
        result = self.deserialize_output(self.ctx.vars.instance, client_flatten=True)
        return result

    class ScanV2sGet(AAZHttpOperation):
        CLIENT_TYPE = "MgmtClient"

        def __call__(self, *args, **kwargs):
            request = self.make_request()
            session = self.client.send_request(request=request, stream=False, **kwargs)
            if session.http_response.status_code in [200]:
                return self.on_200(session)

            return self.on_error(session.http_response)

        @property
        def url(self):
            return self.client.format_url(
                "/{resourceId}/providers/Microsoft.Security/sqlVulnerabilityAssessments/default/scans/{scanId}",
                **self.url_parameters
            )

        @property
        def method(self):
            return "GET"

        @property
        def error_format(self):
            return "MgmtErrorFormat"

        @property
        def url_parameters(self):
            parameters = {
                **self.serialize_url_param(
                    "resourceId", self.ctx.args.resource_id,
                    required=True,
                ),
                **self.serialize_url_param(
                    "scanId", self.ctx.args.scan_id,
                    required=True,
                ),
            }
            return parameters

        @property
        def query_parameters(self):
            parameters = {
                **self.serialize_query_param(
                    "databaseName", self.ctx.args.database_name,
                ),
                **self.serialize_query_param(
                    "api-version", "2026-04-01-preview",
                    required=True,
                ),
            }
            return parameters

        @property
        def header_parameters(self):
            parameters = {
                **self.serialize_header_param(
                    "Accept", "application/json",
                ),
            }
            return parameters

        def on_200(self, session):
            data = self.deserialize_http_content(session)
            self.ctx.set_var(
                "instance",
                data,
                schema_builder=self._build_schema_on_200
            )

        _schema_on_200 = None

        @classmethod
        def _build_schema_on_200(cls):
            if cls._schema_on_200 is not None:
                return cls._schema_on_200

            cls._schema_on_200 = AAZObjectType()

            _schema_on_200 = cls._schema_on_200
            _schema_on_200.id = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200.name = AAZStrType(
                flags={"read_only": True},
            )
            _schema_on_200.properties = AAZObjectType()
            _schema_on_200.system_data = AAZObjectType(
                serialized_name="systemData",
                flags={"read_only": True},
            )
            _schema_on_200.type = AAZStrType(
                flags={"read_only": True},
            )

            properties = cls._schema_on_200.properties
            properties.database = AAZStrType()
            properties.end_time = AAZStrType(
                serialized_name="endTime",
            )
            properties.high_severity_failed_rules_count = AAZIntType(
                serialized_name="highSeverityFailedRulesCount",
            )
            properties.is_baseline_applied = AAZBoolType(
                serialized_name="isBaselineApplied",
            )
            properties.last_scan_time = AAZStrType(
                serialized_name="lastScanTime",
            )
            properties.low_severity_failed_rules_count = AAZIntType(
                serialized_name="lowSeverityFailedRulesCount",
            )
            properties.medium_severity_failed_rules_count = AAZIntType(
                serialized_name="mediumSeverityFailedRulesCount",
            )
            properties.server = AAZStrType()
            properties.sql_version = AAZStrType(
                serialized_name="sqlVersion",
            )
            properties.start_time = AAZStrType(
                serialized_name="startTime",
            )
            properties.state = AAZStrType()
            properties.total_failed_rules_count = AAZIntType(
                serialized_name="totalFailedRulesCount",
            )
            properties.total_passed_rules_count = AAZIntType(
                serialized_name="totalPassedRulesCount",
            )
            properties.total_rules_count = AAZIntType(
                serialized_name="totalRulesCount",
            )
            properties.trigger_type = AAZStrType(
                serialized_name="triggerType",
            )

            system_data = cls._schema_on_200.system_data
            system_data.created_at = AAZStrType(
                serialized_name="createdAt",
            )
            system_data.created_by = AAZStrType(
                serialized_name="createdBy",
            )
            system_data.created_by_type = AAZStrType(
                serialized_name="createdByType",
            )
            system_data.last_modified_at = AAZStrType(
                serialized_name="lastModifiedAt",
            )
            system_data.last_modified_by = AAZStrType(
                serialized_name="lastModifiedBy",
            )
            system_data.last_modified_by_type = AAZStrType(
                serialized_name="lastModifiedByType",
            )

            return cls._schema_on_200


class _ShowHelper:
    """Helper class for Show"""


__all__ = ["Show"]
