variables:
- template: ${{ variables.Pipeline.Workspace }}/.azure-pipelines/templates/variables.yml
- name: Codeql.Enabled
  value: false
- name: ComponentDetection.ForceScan
  value: eq(variables['Build.SourceBranch'], 'refs/heads/release')

parameters:
- name: architectures
  type: object
  default:
  - name: AMD64
    value: amd64
    pool: pool-ubuntu-latest-multi-core
  - name: ARM64
    value: arm64
    pool: pool-ubuntu-latest-arm64
- name: ShouldTest
  displayName: Test?
  type: boolean
  default: false

jobs:

- job: GetAzCliVersion
  displayName: Get Azure CLI Version
  pool:
    name: ${{ variables.ubuntu_pool }}
  steps:
  - checkout: none
  - task: Bash@3
    name: GetAzCliVersion
    displayName: Get Azure CLI Version
    inputs:
      targetType: 'inline'
      script: |
        curl -o __main__.py https://raw.githubusercontent.com/$BUILD_REPOSITORY_NAME/$BUILD_SOURCEBRANCH/src/azure-cli/azure/cli/__main__.py
        ver=`cat __main__.py | grep __version__ | sed s/' '//g | sed s/'__version__='// |  sed s/\"//g`
       
        echo "Extracted Azure CLI version: $ver"
        echo "##vso[task.setvariable variable=AzCliVersion]$ver"
        echo "##vso[task.setvariable variable=AzCliVersion;isOutput=true]$ver"

- job: BuildRpmPackagesAzureLinux
  displayName: Build Rpm Package
  strategy:
    matrix:
      ${{ each arch in parameters.architectures }}:
        Azure Linux 3.0 ${{ arch.name }}:
          image: mcr.microsoft.com/azurelinux/base/core:3.0
          artifact: rpm-azurelinux3.0-${{ arch.value }}
          pool: ${{ arch.pool }}
  pool:
    name: $(pool)
  steps:
  - bash: ./scripts/ci/install_docker.sh
    displayName: Install Docker

  - task: PipAuthenticate@1
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release')
    displayName: 'Pip Authenticate'
    inputs:
      artifactFeeds: $(AZURE_ARTIFACTS_FEEDS)

  - task: Bash@3
    displayName: 'Build Rpm Package: Azure Linux'
    inputs:
      targetType: 'filePath'
      filePath: scripts/release/rpm/pipeline_azurelinux.sh

  - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
    displayName: 'SBOM'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release')
    inputs:
      BuildDropPath: $(Build.ArtifactStagingDirectory)

  - task: PublishPipelineArtifact@0
    displayName: 'Publish Artifact: rpm-azurelinux'
    inputs:
      TargetPath: $(Build.ArtifactStagingDirectory)
      ArtifactName: $(artifact)

- job: BuildDockerImageAzureLinux
  displayName: Build Docker Image Azure Linux
  dependsOn: BuildRpmPackagesAzureLinux
  strategy:
    matrix:
      ${{ each arch in parameters.architectures }}:
        Azure Linux 3.0 ${{ arch.name }}:
          pool: ${{ arch.pool }}
          artifactName: docker-azurelinux3.0-${{ arch.value }}
          dockerfile: azure-linux.dockerfile
          packageArtifactName: rpm-azurelinux3.0-${{ arch.value }}
          image: mcr.microsoft.com/azurelinux/base/core:3.0
  pool:
    name: $(pool)
  steps:
    - bash: ./scripts/ci/install_docker.sh
      displayName: Install Docker
    - task: DownloadPipelineArtifact@1
      displayName: 'Download Build Artifacts'
      inputs:
        TargetPath: '$(Build.ArtifactStagingDirectory)/docker'
        artifactName: $(packageArtifactName)
    - bash: |
        set -ex
        mkdir docker-temp
        mv $(Build.ArtifactStagingDirectory)/docker/*.rpm ./docker-temp/azure-cli.rpm
        
        bash scripts/release/docker/pipeline.sh
      displayName: 'Build Docker'

    - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
      displayName: 'SBOM'
      condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release')
      inputs:
        BuildDropPath: $(Build.ArtifactStagingDirectory)
        DockerImagesToScan: 'clibuild$BUILD_BUILDNUMBER:latest'

    - task: PublishPipelineArtifact@0
      inputs:
        TargetPath: $(Build.ArtifactStagingDirectory)
        ArtifactName: $(artifactName)

- job: TestRpmPackagesAzureLinux
  displayName: Test Rpm Package
  timeoutInMinutes: 180
  dependsOn:
  - BuildRpmPackagesAzureLinux
  - GetAzCliVersion
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI', 'Manual', 'Schedule'), eq(${{parameters.ShouldTest}}, true))
  pool:
    name: $(pool)
  strategy:
    matrix:
      ${{ each arch in parameters.architectures }}:
        Azure Linux 3.0 ${{ arch.name }}:
          image: mcr.microsoft.com/azurelinux/base/core:3.0
          artifact: rpm-azurelinux3.0-${{ arch.value }}
          pool: ${{ arch.pool }}
  variables:
    AzCliVersion: $[ dependencies.GetAzCliVersion.outputs['GetAzCliVersion.AzCliVersion'] ]
  steps:
  - task: DownloadPipelineArtifact@1
    displayName: 'Download Metadata'
    inputs:
      TargetPath: '$(Build.ArtifactStagingDirectory)/metadata'
      artifactName: metadata

  - task: DownloadPipelineArtifact@1
    displayName: 'Download Build Artifacts'
    inputs:
      TargetPath: '$(Build.ArtifactStagingDirectory)/rpm'
      artifactName: $(artifact)

  - bash: ./scripts/ci/install_docker.sh
    displayName: Install Docker

  - bash: |
      set -ex
      RPM_NAME=$(find $SYSTEM_ARTIFACTSDIRECTORY/rpm/ -type f -name "azure-cli-$(AzCliVersion)-1.*.rpm" -printf '%f\n')

      echo "== Test rpm package on ${IMAGE} =="
      docker pull $IMAGE
      docker run --rm -e RPM_NAME=$RPM_NAME -v $SYSTEM_ARTIFACTSDIRECTORY/rpm:/mnt/rpm -v $(pwd):/azure-cli $IMAGE /bin/bash /azure-cli/scripts/release/rpm/test_azurelinux_in_docker.sh

    displayName: 'Test Rpm Package Azure Linux'

- job: TestDockerImageAzureLinux
  displayName: Test Docker Image Azure Linux
  condition: and(succeeded(), eq(${{parameters.ShouldTest}}, true))
  timeoutInMinutes: 180
  dependsOn:
    - BuildDockerImageAzureLinux
    - GetAzCliVersion
  strategy:
    matrix:
      ${{ each arch in parameters.architectures }}:
        Azure Linux 3.0 ${{ arch.name }}:
          pool: ${{ arch.pool }}
          artifactName: docker-azurelinux3.0-${{ arch.value }}
  pool:
    name: $(pool)
  variables:
    AzCliVersion: $[ dependencies.GetAzCliVersion.outputs['GetAzCliVersion.AzCliVersion'] ]
  steps:
    - task: DownloadPipelineArtifact@1
      displayName: 'Download Metadata'
      inputs:
        TargetPath: '$(Build.ArtifactStagingDirectory)/metadata'
        artifactName: metadata

    - task: DownloadPipelineArtifact@1
      displayName: 'Download Docker Image'
      inputs:
        TargetPath: '$(Build.ArtifactStagingDirectory)/docker'
        artifactName: $(artifactName)

    - bash: ./scripts/ci/install_docker.sh
      displayName: Install Docker

    - bash: |
        set -exv
        
        IMAGE_NAME=clibuild$BUILD_BUILDNUMBER:latest
        TAR_FILE="$SYSTEM_ARTIFACTSDIRECTORY/docker/docker-azure-cli-$(AzCliVersion).tar"
        
        echo "== Test docker image =="
        
        docker load < $TAR_FILE
        
        echo "== Run az self-test  =="
        docker run $IMAGE_NAME /bin/bash -c "time az self-test && time az --version && tdnf list --installed"
        
        echo "== Run unit test =="
        docker run --rm -v $(pwd):/azure-cli $IMAGE_NAME /bin/bash /azure-cli/scripts/release/rpm/test_azurelinux_in_docker.sh --InstallRPM false
        
      displayName: 'Bash Script'

- job: BuildCopaPatchedDockerImageAzureLinux
  displayName: Build Copa Patched Docker Image Azure Linux
  timeoutInMinutes: 180
  dependsOn:
    - BuildDockerImageAzureLinux
    - GetAzCliVersion
  strategy:
    matrix:
      ${{ each arch in parameters.architectures }}:
        Azure Linux 3.0 ${{ arch.name }}:
          pool: ${{ arch.pool }}
          artifactName: docker-azurelinux3.0-${{ arch.value }}
          architecture: ${{ arch.value }}
  pool:
    name: $(pool)
  variables:
    AzCliVersion: $[ dependencies.GetAzCliVersion.outputs['GetAzCliVersion.AzCliVersion'] ]
  steps:
    - task: DownloadPipelineArtifact@1
      displayName: 'Download Docker Image'
      inputs:
        TargetPath: '$(Build.ArtifactStagingDirectory)/docker'
        artifactName: $(artifactName)

    - bash: ./scripts/ci/install_docker.sh
      displayName: Install Docker

    - task: Bash@3
      displayName: Install PowerShell for ARM64 Agent
      condition: and(succeeded(), eq(variables['architecture'], 'arm64'))
      inputs:
        targetType: 'inline'
        script: |
          curl -L -o /tmp/powershell.tar.gz https://github.com/PowerShell/PowerShell/releases/download/v7.4.11/powershell-7.4.11-linux-arm64.tar.gz
          sudo mkdir -p /opt/microsoft/powershell/7
          sudo tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7
          sudo chmod +x /opt/microsoft/powershell/7/pwsh
          sudo ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh
          PATH=/usr/bin:/sbin:/usr/sbin:$PATH

    - task: Bash@3
      displayName: Install Az.Accounts for ARM64 Agents
      condition: and(succeeded(), eq(variables['architecture'], 'arm64'))
      inputs:
        targetType: 'inline'
        script: |
          pwsh -command 'Register-PSRepository -Default -InstallationPolicy Trusted'
          pwsh -command 'Install-Module -Name Az.Accounts -Repository PSGallery -AllowClobber -Force'

    - task: Bash@3
      displayName: Install Trivy
      inputs:
        targetType: 'inline'
        script: |
          set -eux
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
          echo "----------------------------------"
          sudo trivy --version

    - task: Bash@3
      displayName: Install copacetic
      inputs:
        targetType: 'inline'
        script: |
          CopaDownloadUrl="https://github.com/project-copacetic/copacetic/releases/download/v$(CopaVersion)/copa_$(CopaVersion)_linux_amd64.tar.gz"
          if [ "$(CPUArchitecture)" = "arm64" ]; then
            CopaDownloadUrl="https://github.com/project-copacetic/copacetic/releases/download/v$(CopaVersion)/copa_$(CopaVersion)_linux_arm64.tar.gz"
          fi
          curl -L -o /tmp/copa.tar.gz $CopaDownloadUrl
          sudo mkdir -p /opt/copacetic
          sudo tar zxf /tmp/copa.tar.gz -C /opt/copacetic
          sudo chmod +x /opt/copacetic/copa
          sudo ln -s /opt/copacetic/copa /usr/bin/copa
          PATH=/usr/bin:/sbin:/usr/sbin:$PATH
          echo "----------------------------------"
          sudo copa --version
          echo "----------------------------------"
          sudo copa --help
          echo "----------------------------------"
          sudo copa patch --help
          echo "----------------------------------"

    - task: Bash@3
      displayName: Check Docker Image
      inputs:
        targetType: 'inline'
        script: |
          set -exv
          
          IMAGE_NAME=clibuild$BUILD_BUILDNUMBER:latest
          TAR_FILE=$SYSTEM_ARTIFACTSDIRECTORY/docker/docker-azure-cli-$(AzCliVersion).tar
          
          echo "== Test docker image =="
          
          docker load < $TAR_FILE
          echo "== docker image =="
          docker images
          echo "== docker container =="
          docker ps
