            - name: Azure CLI Action
  uses: Azure/cli@v2.0.0
  with:
    # Specify the script here
    inlineScript: 
    # Azure CLI version to be used to execute the script. If not provided, latest version is used
    azcliversion: agentazcliversion
          
