name: Block PR merging on blocked labels

on:
  pull_request:
    types: [labeled, unlabeled]
    branches:
      - dev
      - release

permissions: {}

jobs:
  block-merge:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Check blocked labels
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7.1.0
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            const blockedLabels = ["do-not-merge", "needs-author-feedback"];
            
            if (labels.some(label => blockedLabels.includes(label))) {
              console.log(`It is not allowed to merge a PR with any blocked labels: ${blockedLabels}`);
              process.exit(1); // Exit with a non-zero status code to block merge
            } else {
              console.log("It is allowed to merge the PR.");
            }
